#!/bin/bash

# Hostname ändern
echo "server" > /etc/hostname
sed -i 's/127.0.1.1.*/127.0.1.1 server/' /etc/hosts

# Netzwerkschnittstelle konfigurieren
ip addr add 192.168.73.2/24 dev ens4     # L2-DMZ-Network
ip link set ens4 up

# IP-Einstellungen dauerhaft speichern
cat <<EOT >> /etc/network/interfaces
auto ens4
iface ens4 inet static
    address 192.168.73.2
    netmask 255.255.255.0
    gateway 192.168.73.1
EOT

# Sudo installieren und für den Benutzer 'user' erlauben
apt update && apt install sudo -y
usermod -aG sudo user

# Prüfen der Konfiguration
ip addr show
ip route show
ss -tuln
